runner:
  type: local
  usePhantomJS: false
  useChrome: true
  useFirefox: true
  android:
    home: PATH/TO/ANDROIDHOME
    toolsVersion: 4.4
autoCloseDrivers: true
jsonReportSavePath: /some/path/target/RMTReports
RmReportIP: 127.0.0.1
RmReportLivePort: 12345
